homepage:
  path: /
  controller: App\Controller\HomepageController:index

app_logout:
  path: /logout

login:
  path: /login
  controller: App\Controller\SecurityController:login

pages_automatization:
  path: /automatization/pages
  controller: App\Controller\PagesAutomatizationController:index

facebook_auth:
  path: /facebook/auth
  controller: App\Controller\FacebookAuthController:index

facebook_auth_callback:
  path: /facebook/authorize
  controller: App\Controller\FacebookAuthController:authorize

facebook_usertest:
  path: /facebook/usertest
  controller: App\Controller\FacebookAuthController:userTest
